---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'subprojects/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'subprojects/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get install -y --no-install-recommends \
            meson \
            libfmt-dev \
            libsystemd-dev \
            libpq-dev \
            libmd-dev \
            libsodium-dev \
            libluajit-5.1-dev

      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          setup-options: -Dwrap_mode=nofallback -Dsystemd=enabled -Dpg=enabled
